### ISSUE TITLE
does py_ti look at the future?

### ISSUE THREAD

**Issue by makovez** [tlpcap/py_ti#1]
Hi, I really appreciate your work.

We are using your project for a machine learning project. I would like to know if py_ti, in each point. Does it use futures points to assign some technical indicators or only past points?

So for example, let's say we calculate all the technical indicators in all the dataset.

If we look at the technical indicators in candle x, is it possible that some of those technical indicators have used candles after x (x +1, x+2, ...) to calculate them?

**Comment by tlpcap** [comment]
Hi. None of the features look ahead, but they could. They only look at what you feed into them so you could feed in future predictions by shifting your dataframe column.

**Comment by makovez** [comment]
Because I tried the following:

Same dataset A

I create all technical indicators from py_ti from dataset A.

Then i do the same but for dataset A until a fixed row, for example 1000.

Then i compare the two dataset until row 1000.

The technical indicators seems all the same except ti_ease_of_movement_14

Are you sure it doesn't look at the future for that indicator?

**Comment by tlpcap** [comment]
Ok. I'll take a look tomorrow and let you know. You may have found a bug!

**Comment by makovez** [comment]
Thanks, let me know if you find anything

**Comment by tlpcap** [comment]
The volume is scaled using a max absolute scaling method. This was incorporated to allow the user to compare one security to another. Traditionally, volume is not scaled in this indicator. I added a boolean 'scaled' to the function. The default is False. This should resolve your issue. Switch it to True to compare securities, False otherwise.

**Comment by makovez** [comment]
I have added a comment in the commit. Doesen't .shift(1) look at the future next candle?

**Comment by tlpcap** [comment]
I have left a reply comment. You should play with some Pandas methods a bit to better understand what is happening. Short answer is no.
